language: node_js
sudo: false
node_js:
  - 7.7.3
cache:
  directories:
    - bower_components
env:
  global:
    - TZ=America/Los Angeles
install: npm install
script:
  - npm install grunt-cli -g
  - npm install bower -g
  - bower install
  - npm test
branches:
  only:
    - master
